import { heroui } from "@heroui/theme";
import {
  themeColors,
  themeShadows,
  themeGradients,
  primitiveColors,
  scrollbarColors,
} from "./styles/tokens.mjs";

/** @type {import("tailwindcss").Config} */
export default {
  content: [
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "2rem",
        lg: "4rem",
        xl: "5rem",
        "2xl": "6rem",
      },
    },
    extend: {
      colors: {
        canvas: themeColors.retro.bg,
        retro: {
          bg: themeColors.retro.bg,
          paper: themeColors.retro.paper,
          ink: themeColors.retro.ink,
          muted: themeColors.retro.muted,
          pink: themeColors.retro.pink,
          "pink-hover": themeColors.retro.pinkHover,
          sage: themeColors.retro.sage,
          "sage-dark": themeColors.retro.sageDark,
          "sage-ink": themeColors.retro.sageInk,
          dark: themeColors.retro.dark,
          "dark-border": themeColors.retro.darkBorder,
          "muted-light": themeColors.retro.mutedLight,
          body: themeColors.retro.body,
          "body-subtle": themeColors.retro.bodySubtle,
          border: themeColors.retro.border,
          "prose-heading": themeColors.retro.proseHeading,
          "prose-body": themeColors.retro.proseBody,
          "prose-link-hover": themeColors.retro.proseLinkHover,
          "prose-quote-bg": themeColors.retro.proseQuoteBg,
          "prose-quote-text": themeColors.retro.proseQuoteText,
        },
        primary: {
          DEFAULT: themeColors.retro.pink, // Warm salmon-pink
          hover: themeColors.retro.pinkHover,
          50: "#fff0f4",
          100: "#ffdfe7",
          200: "#ffbfd0",
          300: "#ff90ae",
          400: themeColors.retro.pink,
          500: themeColors.retro.pinkHover,
          600: "#cf4668",
          700: "#ac324f",
          800: "#8e2b43",
          900: "#77283c",
        },
        surface: {
          DEFAULT: themeColors.retro.paper,
          resting: themeColors.retro.bg,
          elevated: themeColors.retro.paper,
          hover: "#F5F2EB",
        },
        border: {
          DEFAULT: themeColors.retro.border,
          resting: themeColors.retro.border,
          hover: themeColors.retro.pink,
        },
        text: {
          DEFAULT: themeColors.retro.ink,
          heading: themeColors.retro.ink,
          body: themeColors.retro.body,
          muted: themeColors.retro.muted,
        },
        heading: themeColors.retro.ink,
        body: themeColors.retro.body,
        warning: {
          DEFAULT: "#F3B700",
          50: "#fff8e6",
          100: "#ffebba",
          200: "#fddb7a",
          300: "#fcca3a",
          400: "#f3b700",
          500: "#c99300",
          600: "#a07200",
          700: "#775300",
          800: "#503600",
          900: "#3a2800",
        },
        muted: {
          DEFAULT: "#8899A6",
          50: "#f0f2f3",
          100: "#d6dcde",
          200: "#aeb6ba",
          300: "#8e989c",
          400: "#77878B",
          500: "#8899A6",
          600: "#475255",
          700: "#333c3e",
          800: "#212828",
          900: "#151919",
        },
        linkedin: themeColors.linkedin,
        black: "#000000",
        white: themeColors.retro.paper,
        primitive: {
          "violet-from": primitiveColors.violet.from,
          "violet-to": primitiveColors.violet.to,
          "yellow-from": primitiveColors.yellow.from,
          "yellow-to": primitiveColors.yellow.to,
          "blue-from": primitiveColors.blue.from,
          "blue-to": primitiveColors.blue.to,
          "cyan-from": primitiveColors.cyan.from,
          "cyan-to": primitiveColors.cyan.to,
          "green-from": primitiveColors.green.from,
          "green-to": primitiveColors.green.to,
          "pink-from": primitiveColors.pink.from,
          "pink-to": primitiveColors.pink.to,
          "foreground-from": primitiveColors.foreground.from,
          "foreground-to": primitiveColors.foreground.to,
        },
        scrollbar: {
          thumb: scrollbarColors.thumb,
          "thumb-hover": scrollbarColors.thumbHover,
        },
      },
      boxShadow: {
        "retro-xs": themeShadows.retroXs,
        "retro-sm": themeShadows.retroSm,
        retro: themeShadows.retro,
        "retro-md": themeShadows.retroMd,
        "retro-5": themeShadows.retro5,
        "retro-lg": themeShadows.retroLg,
        "retro-xl": themeShadows.retroXl,
      },
      backgroundImage: {
        "retro-haze": themeGradients.retroHaze,
      },
      borderRadius: {
        "2xl": "1rem",
        full: "9999px",
        card: "1rem",
        container: "1rem",
        pill: "9999px",
        button: "9999px",
      },
      fontFamily: {
        sans: [
          "var(--font-sans)",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          "sans-serif",
        ],
        mono: [
          "var(--font-mono)",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
        logo: ["var(--font-logo)"],
      },
    },
  },
  darkMode: "class",
  plugins: [heroui({ prefix: "ik" })],
};
